DROP SCHEMA IF EXISTS PROJECT;
CREATE SCHEMA PROJECT default character set utf8;
USE PROJECT;

CREATE TABLE USERTBL (
	USER_ID INT PRIMARY KEY,
    USER_PASSWORD VARCHAR(15) NOT NULL,
    USER_NAME VARCHAR(15) NOT NULL,
    USER_BIRTH DATE NOT NULL,
    USER_PHONE CHAR(11) NOT NULL,
    USER_LICENSE CHAR(15) UNIQUE
);



CREATE TABLE PLACETBL (
	PLACE_ID INT PRIMARY KEY,
    PLACE_NAME VARCHAR(10) NOT NULL
);

CREATE TABLE VEHICLETBL (
	VEH_ID INT NOT NULL,
	VEH_MODEL VARCHAR(10) NOT NULL,
    VEH_DEFPLACE INT NOT NULL,
    VEH_PLACE VARCHAR(10) NOT NULL,
	VEH_BATT INT NOT NULL DEFAULT 100,
    VEH_STATE VARCHAR(5) NOT NULL DEFAULT '정상',
    VEH_RESERVE CHAR(1) NOT NULL DEFAULT 'x',
    VEH_USING CHAR(1) NOT NULL DEFAULT 'x',
    PRIMARY KEY (VEH_ID),
    FOREIGN KEY (VEH_DEFPLACE) REFERENCES PLACEtbl(PLACE_ID) on delete cascade on update cascade
);

CREATE TABLE RESERVETBL (
	RES_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    VEH_ID INT NOT NULL,
    RES_TIME DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERtbl(USER_ID) on delete cascade on update cascade, 
    FOREIGN KEY (VEH_ID) REFERENCES VEHICLEtbl(VEH_ID) on delete cascade on update cascade
);


CREATE TABLE RENTALTBL (
	REN_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    VEH_ID INT NOT NULL,
    ren_STIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ren_SPLACE VARCHAR(10) NOT NULL,
    RES_NUM INT UNIQUE,
    FOREIGN KEY (USER_ID) REFERENCES USERtbl(USER_ID) on delete cascade on update cascade,
    FOREIGN KEY (VEH_ID) REFERENCES VEHICLEtbl(VEH_ID) on delete cascade on update cascade,
    foreign key (res_num) references reservetbl(res_num) on delete cascade on update cascade
);

CREATE TABLE returntbl (
	rtn_NUM INT NOT NULL PRIMARY KEY,
    rtn_ETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rtn_EPLACE VARCHAR(10) NOT NULL,
    rtn_DIST INT NOT NULL,
    rtn_PRICE NUMERIC(9,2),
    foreign key (rtn_num) references rentaltbl(ren_num) on delete cascade on update cascade 
);



COMMIT;